### ISSUE TITLE
300km/h HSR engine expires but not coaches

### ISSUE THREAD

**Issue by xsrvmy** [andythenorth/iron-horse#12]
If I start a game at say 3000, the coaches for the 300 km/h train shows up, but not the engines. The 200 km/h diesel engine shows up though.

**Comment by andythenorth** [comment]
That's lol, thanks for the report😉

Unsure of cause or fix, so I'll leave this open for now.

**Comment by andythenorth** [comment]
Definitely a mystery this one :)  Can't find any fix, but thanks for reporting 👍
