### ISSUE TITLE
[Suggestion] Remove cart reskins in gameplay-optimized mode

### ISSUE THREAD

**Issue by Charanor** [andythenorth/iron-horse#18]
Playing 3.0 with simplified gameplay flag set, I notice that there are a LOT of carts that are exactly the same, but just reskins, such as:
- Hopper
- Ore hopper
- Mineral wagon
- Ore dump wagon
- etc.

It's nice to have the options when I want to design something pretty but for simplified gameplay I think removing all but one of these as well as the "brake van" is a good idea.

Cheers!

**Comment by andythenorth** [comment]
https://github.com/andythenorth/iron-horse/commit/74edc3e4000a8aff296eee356415ef3c300df422
