### ISSUE TITLE
One of Girt Licker variants not available in arctic

### ISSUE THREAD

**Issue by EmperorJake** [andythenorth/iron-horse#19]
Version 3.1.0, arctic climate only, there is only one Girt Licker variant available. Appears to work correctly in all other climates.
<img width="446" alt="image" src="https://github.com/andythenorth/iron-horse/assets/68182631/918f6751-29bc-4623-af6a-3ab84ee05afc">

**Comment by andythenorth** [comment]
Too weird for words sorry, there's no climate-dependent stuff checking Arctic 😄
