### ISSUE TITLE
grf.farm  guidelines impossible to follow

### ISSUE THREAD

**Issue by matematysek** [andythenorth/iron-horse#21]
"Compiling

Iron Horse source includes a makefile for convenient building. This requires '[Make](https://en.wikipedia.org/wiki/Make_(software))', typically provided by the ports tree on Linux / Unix, [MSYS](http://www.mingw.org/wiki/msys) on Windows and [Xcode](https://developer.apple.com/xcode/) on macOS."

MSYS leads to dead site...

**Comment by AjinxPatil** [comment]
I was able to compile this project just yesterday. I admit, it was not easy. There were lot of obstacles like Python versions and packaging, dependency issues and WSL gotchas. But given the complications and the fact that process varies with different system setups and versions, and things change with time, I don't expect the creator to explain every single step.

You can either use https://www.msys2.org/ or WSL 2.

**Comment by andythenorth** [comment]
Updated docs in 3ebb793a044413e8515328c8bb7db157501caeaf
