### ISSUE TITLE
Some specific Hopper cars load slower than the general Hopper car

### ISSUE THREAD

**Issue by rpwjanzen** [andythenorth/iron-horse#7]
Some specific hopper types (Covered, Grain, Pellet, Carbon Black, Potash)  load slower than the general Hopper.
The specific [hopper types](https://grf.farm/iron-horse/2.27.0/html/code_reference.html) load at speed 7 whereas the general Hopper cars load at speed 10.

I find this surprising as I'd assume that the hopper that has a limited set of cargo that it can transport would be "optimized" for the cargo compared to the general hopper that would be "unoptimized" and can be refitted to transport more kinds of cargo.

Is is a valid assumption?

**Comment by andythenorth** [comment]
Changed them to 10, because 'why not?'.  Cheers.
